apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db  
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
       component: mysql
       project: expense
       tier: db  
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentvolumeClaim:
          claimName: mysql